Change testing structure + add HIV+ hiv pos
mrc-ide/leaptfrog pull request #14
Opened 2022-06-30 13:55 UTC by mwalte10

- Modified testthat file structure so that the demo and transmission models can be done repeatedly on different iterations
- Includes writing out those csvs we talked about during 1:1
- Also included in this push is the adding hiv+ 15 yo entrants
- Rob mentioned that there is a preference for library:: over loading it at the beginning but calling dplyr that way feels a bit silly in the helper file so lmk your thoughts there

2022-07-05 23:07 UTC, jeffeaton requested changes
Thanks, good stuff. Ping me if useful to discuss together more about the comments (I suspect it will be).

For the new test PJNZ file that is added, can you please add a description in the README here about what the specification of the file is / what the purpose of the file is to test: https://github.com/mwalte10/leapfrog/blob/dev_add_hivp_entrant/tests/testdata/spectrum/README.md   (Sorry, I have not been as careful as I would like with that file yet; will aim to clean it up more.)

2022-07-05 23:07 UTC, jeffeaton commented on DESCRIPTION
> +    cubelyr
Are these packages added only for use in tests?  If so, I _think_ they can be under `Suggests:` rather than `Imports:`.

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/test-spectrum.R
> +  demo_matches_totpop("../testdata/spectrum/v6.13/bwa_demproj-only-no-mig_spectrum-v6.13_2022-02-12.PJNZ")
Can we as @r-ash for style input on this? 

To me, moving the `expect_*()` assertions to helper functions obscures the tests and I am concerned if it might it more difficult to identify where the failure occurred and debug.

But I see your point that we don't want to duplicate blocks of test code that will be run on multiple scenarios.

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +demo_matches_totpop <- function(pjnz){
does `demo_` refer to _demography_ here?  Can we change it to at least `demog_` for clarity?

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +demo_matches_totpop <- function(pjnz){
Actually, on second read I don't know if it does refer to _demography_. What does it refer to?

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +  ## modifying this because the no art spectrum doesn't pass this. Moved it from 0.001 to 0.01, the max is 0.008
Can you give me code snippet to reproduce this? 

Probably suggest making this a parameter rather than changing the threshold for the existing demography only test.

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/test-spectrum.R
> +  demo_matches_totpop("../testdata/spectrum/v6.13/bwa_demproj-only-no-mig_spectrum-v6.13_2022-02-12.PJNZ")
For example on this, I uncommented the test below: https://github.com/mrc-ide/leapfrog/blob/51dfb43993f7982e9d83538944d01d6aed38fc92/tests/testthat/test-spectrum.R#L40-L44

And this is all I get back from that test failure: 

```
>   pjnz1 <- "../testdata/spectrum/v6.13/bwa_aim-adult-no-art_spectrum-v6.13_2022-02-12.pjnz"
>   demo_matches_birthsdeaths(pjnz1)
Error: all(...) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
```
Which feels difficult to get into and debug.

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +  print('New deaths comparison file written out to /tests/testdata/plotting_diagnostics')
After reviewing this, as discussed, I am uncertain the value of saving this out as a CSV. And I think definitely do not want to commit it to the Git repo.

I don't see where this is used elsewhere. What is the use case for saving it?  I suspect that a preferred approach will be to create a function that takes either a PJNZ file or some model objects as inputs and returns the data frame you want as an output.

In some cases, if there are slow-to-produce test files, @r-ash will create a script that can be run locally to run once and save the test comparison files instead of running code to produce the file every time test is run.  But from initial review, I don't _think_ saving this is for the same use case.

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +  fp$tARTstart <- 61L
How do you envision this function being reused elsewhere?  

Note that this line sets the time of ART start to year 61 (end of projection), so this will negate any ART inclusion in the EPP simulation. Suspect that might not be desired in subsequent use of this function.

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +    dplyr::as_tibble() %>%
I am not necessarily opposed to bringing `cubelyr` into our stack, but unless we are using more advanced features, I suggest replacing these lines with the base R version:

```
as.data.frame.table(mod_prev, responseName = "EPPASM")
```

I think it produces the same output as the `as.tbl_cube() %>% as_tibble()` chain:

```
Browse[2]> as.data.frame.table(mod_prev, responseName = "EPPASM")
     CD4 eppasm_age sex year       EPPASM
1      1          1   1    1 0.000000e+00
2      2          1   1    1 0.000000e+00
3      3          1   1    1 0.000000e+00
4      4          1   1    1 0.000000e+00
5      5          1   1    1 0.000000e+00
6      6          1   1    1 0.000000e+00
7      7          1   1    1 0.000000e+00
```

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +  dimnames(lmod_prev) <- list('CD4' = c(1:7), 'leapfrog_age' = c(1:66), 'sex' = c(1:2), 'year' = c(1:61))
We should write a function in the package that assigns dimnames to the `leapfrogR()` return.

Probably make it a an argument to include the dimnames in the output (i.e. something like `leapfrogR(..., add_dimnames = TRUE)`.

2022-07-05 23:07 UTC, jeffeaton commented on tests/testthat/helper-checkfunctions.R
> +  age_mapping <- data.frame(eppasm_age = c(rep(1,2), rep(2,2), unlist(lapply(c(3:8), rep, times = 5)), rep(9, 32)), leapfrog_age = 1:66)
* Small style point -- no need to wrap `c(3:8)` in `c(...)`; I think just `3:8` more readable (relates to many lines below)
* You can replace `unlist(lapply(c(3:8), rep, times = 5))` with `rep(3:8, each = 5)`
* The index mapping you create in `eppasm_age` exists in the `fp$ss$ag.idx`, so you can replace this with:
```
age_mapping <- data.frame(
                  eppasm_age = fp$ss$ag.idx,
                  leapfrog_age = 1:66
                )
```

* But, substantively -- comparing the single-age version of leapfrog with EPP-ASM (coarse age), we shouldn't expect to match in test results. It is close, but the age aggregation in EPP-ASM induces some approximation.  Use the `"coarse"` age stratification version of `leapfrogR` to produce simulation with same dimension as EPP-ASM:

```
  lmod <- leapfrogR(demp, hivp, hiv_strat = "coarse")
```

Can you try with that and see how the tests align?

2022-07-05 23:07 UTC, jeffeaton commented on inst/include/leapfrog-raw.h
> +                    const Type *p_age15hivpop,
From looking at code, this implementation all looks good to me -- good stuff.  But ideally we should create a test file that includes some 'ageing in'  and unit test this before merging.

2022-07-05 23:07 UTC, jeffeaton commented on DESCRIPTION
> +    cubelyr
If these are only being used in tests, I think they can me in `Suggests:` rather than `Imports:`.

Regarding query about referencing functions with `dplyr::` versus putting in `Depends:`, as Rob says, in any package code (anything in `R/`), we tend to use `dplyr::`.  In tests, I feel less strongly about it I think but defer to Rob's guidance.

2022-07-07 09:22 UTC, mwalte10 commented on DESCRIPTION
> +    cubelyr
they were but they actually aren't necessary any more so I will remove them

2022-08-11 10:45 UTC, closed without merging