add functions to read PMTCT and child ART inputs
mrc-ide/leaptfrog pull request #45
Opened 2023-02-19 22:29 UTC by jeffeaton

This PR adds several functions to read the PMTCT, Child ART, breastfeeding percentage, and abortion inputs from Spectrum _Programme statistics_ input editor. 

These are the functions and example usage:

```
pjnz <- system.file("pjnz/bwa2021_v6.13.pjnz", package = "leapfrog")
dp <- read_dp(pjnz)
dp_anc_testing <- dp_read_anc_testing(dp)
dp_pmtct <- dp_read_pmtct(dp)
dp_read_pmtct <- dp_read_pmtct_retained(dp)
dp_abortion <- dp_read_abortion(dp)
dp_notbreastfeeding <- dp_read_breastfeeding(dp)
dp_childart <- dp_read_childart(dp)
dp_childltfu <- dp_read_childltfu(dp)

## Can either pass PJNZ path or parsed "spectrum_dp" object

anc_testing1 <- dp_read_anc_testing(pjnz)
anc_testing2 <- dp_read_anc_testing(dp)
all.equal(anc_testing1, anc_testing2)
```

Things are returned as matrices with rows for indicators and columns for each year---mimicking the input editors in Spectrum.

Please review and let me know:
1. anything doesn't make sense,
2. any inputs you need that are missing,
3. any suggestions for better ways to format
4. anything that is wrong (of course)

A few further notes:
* I have not written tests for these functions yet.
* I have not written code that pulls them together into a set of inputs yet. Can discuss together strategy for that if useful.
* It is written for use with current version of Spectrum. We can add older tags for backward compatibility as needed; let me know.
* Let's Get this merged and pulled into your branches so that you can press ahead. But soon let's try to engage @r-ash to discuss plan for the inputs / outputs. Whether he would like to review the `specio` package for this or we should do something different.

2023-02-20 10:02 UTC, mwalte10 commented on R/read-spectrum.R
> +    dimnames(pmtct_arv) <- list(indicator = pmtct_indicators, year = dpy$proj_years)
Currently I have this set up to have different indexes based on whether the input is a number or percent. I can switch over to this combined way if you think that is cleaner, but not sure in C++ how to grep whether it's a number or percent.

2023-02-20 10:03 UTC, mwalte10 commented on R/read-spectrum.R
> +                        "pmtct_artafter4weeks_percent",
Shouldn't we have a separate prenatal dropout for optionb?

2023-02-20 10:03 UTC, mwalte10 commented on R/read-spectrum.R
> +  if (exists_dptag(dp, "<ARVRegimen MV3>")) {
Not fully understanding this

2023-02-20 10:05 UTC, mwalte10 commented on R/read-spectrum.R
> +  indicator_names <- c("pmtct_retained_alreadyart", "pmtct_retained_newart")
Ah, I think this is the prenatal dropout I was referring to above. I think either we should pull out the postnatal dropouts from dp_read_pmtct or put this in read_pmtct. I'd prefer pulling out postnatal dropouts into this function.

2023-02-20 10:05 UTC, mwalte10 commented on R/read-spectrum.R
> +       pregtermabortion_ispercent = pregtermabortion_ispercent)
Do we want to add years to this list to make it consistent with the other inputs?

2023-02-20 10:10 UTC, mwalte10 commented on R/read-spectrum.R
> +#' @export
Is this file the place to put in any notes about the inputs? like that this is the % no longer breastfeeding and not the % still breastfeeding?

2023-02-20 10:11 UTC, mwalte10 commented on R/read-spectrum.R
> +    dimnames(pmtct_arv) <- list(indicator = pmtct_indicators, year = dpy$proj_years)
Also may be helpful to separate prenatal and postnatal into separate components of a list.

2023-02-20 10:22 UTC, mwalte10 commented on R/read-spectrum.R
> +                       "childart_art0to14",
if possible might make more sense to move 0to14 to the end? to show its a summation

2023-02-20 10:27 UTC, mwalte10 requested changes
A few comments throughout, mostly on structure and grouping of certain inputs. Also added in the inputs that are missing at the bottom (we had talked about them at the beginning but not more recently). Thanks!

2023-02-20 10:27 UTC, mwalte10 commented on R/read-spectrum.R
> +}
We are missing the following: 

Transmission:

- mtct transmission rates
- Distribution of new infections by CD4

Treatment:

- ART initiation by age

Disease progression:

- HIV mortality without ART
- HIV mortality with ART
-        Mortality rate ratios over time
- Disease progression rates

2023-02-20 13:36 UTC, jeffeaton commented on R/read-spectrum.R
> +  if (exists_dptag(dp, "<ARVRegimen MV3>")) {
Which bit not understanding? The comment? 

The first line is a note about how the data values are stored internally in the .DP file. They are 

The second comment is noting that if the value '0' is in the input editor, I interpreted it as 'no value entered' and replaced by NA. (In many of the Spectrum editors, 'no value entered' is stored as -9999. But here it defaults them to 0s.). It might be better to keep them as 0s rather than change to `NA`. What makes sense for how they are used?

2023-02-20 13:45 UTC, jeffeaton commented on R/read-spectrum.R
> +    dimnames(pmtct_arv) <- list(indicator = pmtct_indicators, year = dpy$proj_years)
This is how they are stored internally in the `.DP` file.  I suggest reading them out like this, and then have another function that processes them into the the convenient format for input to simulation model.

Generalizing that, I find that 'pre-processing' step useful for other things. E.g. some rate parameters that are specified in Spectrum by 5-year age group, but in the internals of the model it is more convenient to have them as single-year age parameters (so just increment +1 along a loop).

In general, do as much of that as possible as prep step rather than in the C++. (Try to only iterate over things in the C++, not have to do look up / arithmetic to identify desired indices.)

2023-02-20 13:48 UTC, jeffeaton commented on R/read-spectrum.R
> +       pregtermabortion_ispercent = pregtermabortion_ispercent)
These have `year` as the names attribute on the vector:

```
> dp_abortion$pregtermabortion
1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 
   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0 
1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 
   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0 
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 
   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0 
2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 
   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0 
2030 
   0 

> dp_abortion$pregtermabortion_ispercent
1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 
  NA   NA   NA   NA   NA   NA   NA TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 
TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 
TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 
TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
2030 
TRUE 
```

That is how they have been saved in other vector outputs in the extracts. Open to suggestion for alternative.

2023-02-20 13:50 UTC, jeffeaton commented on R/read-spectrum.R
> +#' @export
Yes, this is the code that generates the R documentation. `@rdname dp_read_anc_testing` means that this function is described in the same documentation as the function `dp_read_anc_testing()`.  So you can add to the `@details` section of the documentation for that function. Or we can make separate documentation for this function. (I was just being a bit lazy about writing the documentation for these.)

2023-02-20 13:51 UTC, jeffeaton commented on R/read-spectrum.R
> +                       "childart_art0to14",
This mirrors the order that they are saved in the `.DP`. General usage of this input in Spectrum is that users will input _either_ the 0-14 total, or the total by 5-year age groups. But I think one or the other is usually left empty.

2023-02-20 13:55 UTC, jeffeaton commented on R/read-spectrum.R
> +  indicator_names <- c("pmtct_retained_alreadyart", "pmtct_retained_newart")
The reason I implemented this way is because it was saved under a different tag.

Two options here:

* Write a wrapper function that reads both and combines them as you like.
* Combine into one function as you suggest.

I don't have a strong feeling about which to do. We will need a wrapper function that reads, processes, and formats everything. But for this one, I agree it could make sense to simply always have the function do both.

2023-02-20 13:56 UTC, jeffeaton commented on R/read-spectrum.R
> +    dimnames(pmtct_arv) <- list(indicator = pmtct_indicators, year = dpy$proj_years)
Similar to comment above (https://github.com/mrc-ide/leapfrog/pull/45#discussion_r1111990336), we could handle in two ways. Let's make a decision about which we want and apply to both.

2023-02-20 15:23 UTC, mwalte10 commented on R/read-spectrum.R
> +    dimnames(pmtct_arv) <- list(indicator = pmtct_indicators, year = dpy$proj_years)
Gotcha, assuming that is what this is for? https://github.com/mrc-ide/leapfrog/blob/master/R/spectrum-inputs.R

2023-02-20 15:25 UTC, mwalte10 commented on R/read-spectrum.R
> +  if (exists_dptag(dp, "<ARVRegimen MV3>")) {
Ah sorry that was so not clear. Was confused why it was doing ARV regimen rather than PMTCT regimen but I see now that's just what it is called.

2023-02-20 15:27 UTC, mwalte10 commented on R/read-spectrum.R
> +       pregtermabortion_ispercent = pregtermabortion_ispercent)
This has bothered me before tbh, I am pro making year the first attribute of a list always if its relevant just to make parsing out indexing easier.

2023-02-20 15:28 UTC, mwalte10 commented on R/read-spectrum.R
> +#' @export
Got it, I can go in and add details once the others are added in.

2023-02-20 16:27 UTC, jeffeaton commented on R/read-spectrum.R
> +    dimnames(pmtct_arv) <- list(indicator = pmtct_indicators, year = dpy$proj_years)
Yep, specifically this: https://github.com/mrc-ide/leapfrog/blob/master/R/spectrum-inputs.R#L140. (Though in further layers of mess, a lot of that is dedicated to adjusting the function that is used to process for EPP-ASM inputs to make some adjustments as required for leapfrog. That's the bit we should make a plan to start to unwind to cut EPP-ASM out of the picture.)

2023-02-23 15:16 UTC, mwalte10 approved these changes

2023-02-23 15:17 UTC, mwalte10 commented
Approving to merge into my branches, copying what is missing below in case it gets lost.

We are missing the following:

Transmission:

mtct transmission rates
Distribution of new infections by CD4
Treatment:

ART initiation by age
Disease progression:

HIV mortality without ART
HIV mortality with ART
   Mortality rate ratios over time
Disease progression rates

2023-02-23 15:17 UTC, merged